import {bug, dark, dragon, electric, fairy, fighting, fire, flying, ghost, grass,
  ground, ice, normal, poison, psychic, rock,steel, water
} from '../assets/pokemon-type/typesvg';

export const typeIcon = {
  normal,
  fighting,
  flying,
  poison,
  ground,
  rock,
  bug,
  ghost,
  steel,
  fire,
  water,
  grass,
  electric,
  psychic,
  ice ,
  dragon,
  dark,
  fairy,
}

export const typeColor = {
  normal: "#949495",
  fighting: "#E09C40",
  flying: "#A2C3E7",
  poison: "#735198",
  ground: "#9C7743",
  rock: "#BFB889",
  bug: "#9FA244",
  ghost: "#684870",
  steel: "#69A9C7",
  fire: "#e56c3e",
  water: "#5185C5",
  grass: "#66A945",
  electric: "#F6D851",
  psychic: "#DD6B7B",
  ice: "#6DC8EB",
  dragon: "#535CA8",
  dark: "#4C4948",
  fairy: "#DAB4D4",
  unknown: "#d5ec6d",
}
